# Generated by Django 3.2.8 on 2021-10-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblogs', '0005_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
